### PR TITLE
CHINESE complete

### PR DESCRIPTION
**Pull request by OPICES**
[Chinese.ZIP](https://github.com/entradainteractive/miscreated-localization/files/3487267/Chinese.ZIP)

### CODE REVIEW

**Comment by csprance** [comment]
Thank you very much for your translations! They will be included in the next patch!

I merged this in separately because you included some random zip files.
In the future please only modify files and do not include new files. This makes the merging process troublesome.

**Comment by csprance** [comment]
https://github.com/entradainteractive/miscreated-localization/commit/9beb3c1735d5ddcec4dd113ac296204b02a556d9

**Comment by OPICES** [comment]
In the future, I will make it ZIP upload. Is that OK?

**Comment by csprance** [comment]
No. No zip. Do not add any new files.

**Pull request closed without merging**
