### PR TITLE
Text UI items

### PR DESCRIPTION
**Pull request by Amoebawp**
Complete reviewed translation by the french community

### CODE REVIEW

**Comment by Amoebawp** [comment]
Hope this time is okay-ish

**Comment by csprance** [comment]
Thank you! I will merge these in shortly.

**Comment by Amoebawp** [comment]
Do you have any news on the rest of the files we have to translate ?

**Comment by csprance** [comment]
@Amoebawp I've merged the pull request and added in some new localization files if you are still interested. Thank you for the great work!

**Comment by Amoebawp** [comment]
@csprance recieved, but i suspect an issue with the item file -- it ends before my version (where we already translated) and doesn't contain the usual endlines for an xml. Maybe you could take a look at this file ?
I'll extract the content of the ingame file and start working on it.
 Thanks again for letting us help you on this task.

**Comment by csprance** [comment]
I'm not sure what you mean exactly by "It Ends before my version"

I'm going to create a new issue for this instead of dealing with it in a closed pull request.

Issue #2

**Pull request merged**
