### PR TITLE
Use this to correct Sorry

### PR DESCRIPTION
**Pull request by OPICES**

### CODE REVIEW

**Comment by OPICES** [comment]
I just found some problems and I resubmitted them. Thank you.

**Comment by csprance** [comment]
Please remove the unneeded zip files. Do not add any new files.

**Comment by OPICES** [comment]
OK

**Comment by csprance** [comment]
I'm not sure which file is the right one so I used chinese3.rar.

Thank you for your contribution but make sure not to add any new files, delete anything and make sure your translations are located in the correct folder. Which in your case the only thing you would need to update are the files in the `Chinese` Folder

I merged this in manually so I'm closing this PR!

Thank you very much! I've added special role to your name in discord as well so people know about your hard work!

**Comment by OPICES** [comment]
This is the most correct use of China.

---Original---

**Pull request closed without merging**
