### PR TITLE
Polish

### PR DESCRIPTION
**Pull request by H4Z4-rd**

### CODE REVIEW

**Comment by csprance** [comment]
These files need to be moved from the root folder into the correct language folder

under Polish

**Comment by H4Z4-rd** [comment]
I know this may seem silly, but I try to do it and I fail. As if I had
blocked access. PitiViers is going to help me, but it's not until next week.

And sorry for the trouble, but I really can't handle these things.

Now in the attachment - the latest version with patches (but still with
HINT in English - I checked this file many times, I even bought Excel, but
in Polish this file just freezes the game).

Piotr Pieńkowski
H4Z4-rd

śr., 28 sie 2019 o 19:00 Chris Sprance <notifications@github.com>
napisał(a):

**Comment by csprance** [comment]
One easy way to manage the files and the git commit etc is to use GitHub Desktop. It will really make it a lot easier to understand what you are doing.

**Comment by csprance** [comment]
Closing due to inaction. Please reopen if this was closed in error.

**Pull request closed without merging**
